### ISSUE TITLE
[meta] Roadmap

### ISSUE THREAD

**Issue by rgaiacs** [GESIS-Methods-Hub/andrew#175]
- [ ] Prototype (v1.0.0)
- [ ] Minimum Viable Product (v2.0.0)
- [ ] Minimum Marketable Product (v3.0.0)
- [ ] Minimum Loveable Product (v4.0.0)
